sudo: required

env:
  global:
    - VERSION_NUMBER="0.1.$TRAVIS_BUILD_NUMBER"

language: csharp
mono: none
solution: DsRule.sln
dotnet: 3.1
install:
  - dotnet restore

script:
  - dotnet build --configuration Release -p:Version=$VERSION_NUMBER
  - dotnet test test/DsRule.UnitTest/DsRule.UnitTest.csproj

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "main" ]; then bash ./deploy.sh; fi'
    
#notifications:
#  email:
#    on_failure: always
#    on_success: never